package cn.ggx.entity;

import java.util.Date;

/**
 * tools_type
 * 
 * @author bianj
 * @version 1.0.0 2021-01-21
 */
public class ToolsType implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 2719977130124234435L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** name */
    private String name;

    /** flag */
    private Integer flag;

    /** cerateTime */
    private Date cerateTime;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取name
     * 
     * @return name
     */
    public String getName() {
        return this.name;
    }

    /**
     * 设置name
     * 
     * @param name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 获取flag
     * 
     * @return flag
     */
    public Integer getFlag() {
        return this.flag;
    }

    /**
     * 设置flag
     * 
     * @param flag
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * 获取cerateTime
     * 
     * @return cerateTime
     */
    public Date getCerateTime() {
        return this.cerateTime;
    }

    /**
     * 设置cerateTime
     * 
     * @param cerateTime
     */
    public void setCerateTime(Date cerateTime) {
        this.cerateTime = cerateTime;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}